# Generated by Django 4.0.4 on 2022-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
